### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by notDavid** [daschr/dnswatch#1]
Hi, i decided to try this for checking if my Pi-hole is working correctly, but i can't get it to work properly;

So, i start the program with `dnswatch @127.0.0.1 reddit.com T30 -c 'echo "changed to $ADDRESS!"'`

`dig +short @127.0.0.1 reddit.com` results in: `0.0.0.0`
Then, i remove reddit.com from the blacklist in Pi-Hole.
`dig +short @127.0.0.1 reddit.com` results in: `151.101.129.140
151.101.65.140
151.101.193.140
151.101.1.140`

However, dnswatch does not do/output anything.

Also, i see in Pi-hole that after a while dnswatch is resolving reddit.com multiple times at once (in the same second). So it's resolving like 12 times at once, instead of 1:
<img width="622" alt="dnswatch" src="https://user-images.githubusercontent.com/1530401/89129027-4ea31300-d4e9-11ea-82c6-2ad2782ffa1d.png">

**Comment by daschr** [comment]
So you waited 30 seconds after the change, and dnswatch did nothing?
To see if a change occured, dnswatch resolves every n seconds specified either by T<secs> or using the default of 60s.

I'll test this now and come back again.

**Comment by notDavid** [comment]
> So you waited 30 seconds after the change, and dnswatch did nothing?

Yes! :)

**Comment by daschr** [comment]
Ok, I have found the issue:
`dnswatch @127.0.0.1 reddit.com T30 -c 'echo "changed to $ADDRESS!"'` 
should be
`dnswatch @127.0.0.1  T30 reddit.com sh -c 'echo "changed to $ADDRESS!"'`

Else dnswatch would try to resolve reddit.com and then run the command: `T30 -c 'echo "changed to $ADDRESS!"'`

Note the calling convention: `dnswatch [@<nameserver>|T<stime>|AAAA] [--] [fqdn] [command] [args]...`
I'll add an check for these cases. ;)

The other problem is that currently multipe A records may be resolved in different order each time. But it should be possible to fix this.

**Comment by notDavid** [comment]
Ahh that explains, thank you! It's working now indeed.

> The other problem is that currently multipe A records may be resolved in different order each time. But it should be possible to fix this.

Indeed, i'm also getting change notifications when nothing changed, because of the "order" problem. Would be nice if you can fix that 👍

**Comment by daschr** [comment]
Nearly done, I will finish it tomorrow.

**Comment by daschr** [comment]
dnswatch now compares all records and stores the records comma-separated in the envvar $ADDRESSES.

Commit: 4cc2845d0ad62dcc9352392350370915983924ef

**Comment by notDavid** [comment]
Great, it's working now, thank you! 🙏🏼

1 minor issue: `$ADDRESS!` is no longer set. It's always an empty value.

```
$ dnswatch @127.0.0.1 T30 reddit.com sh -c 'echo "changed to $ADDRESS!"'
changed to !
changed to !
```

**Comment by daschr** [comment]
`dnswatch @127.0.0.1 T30 reddit.com sh -c 'echo "changed to $ADDRESS!"'`
would now be 
`dnswatch @127.0.0.1 T30 reddit.com sh -c 'echo "changed to $ADDRESSES!"'`

So should I set $ADDRESS to the first changed address?

**Comment by notDavid** [comment]
Oh right i didn't see that, `$ADDRESSES` is perfectly fine i will use that 🙂

Thank you 👍🏼

**Comment by daschr** [comment]
You're welcome. :-)
